"""Add created_at to LeaveRequest

Revision ID: 27cdfa7d227f
Revises: c28285d83f49
Create Date: 2025-05-27 12:54:23.450771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27cdfa7d227f'
down_revision = 'c28285d83f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
