"""Add reporting_manager_id to User

Revision ID: 2e3fae50a70a
Revises: 315fb85252ee
Create Date: 2025-05-26 12:21:26.707530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e3fae50a70a'
down_revision = '315fb85252ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reporting_manager_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['reporting_manager_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reporting_manager_id')

    # ### end Alembic commands ###
