"""Add LeaveBalance table

Revision ID: 315fb85252ee
Revises: 2468aea99c66
Create Date: 2025-05-20 16:22:53.501397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315fb85252ee'
down_revision = '2468aea99c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('used', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('leave_balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_balance', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('leave_balance')
    # ### end Alembic commands ###
