"""Add is_read column to LeaveRequest

Revision ID: c28285d83f49
Revises: 2e3fae50a70a
Create Date: 2025-05-27 12:52:07.165115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c28285d83f49'
down_revision = '2e3fae50a70a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
